### ISSUE TITLE
Entering tab from last field of non-last row causes new row to be added

### ISSUE THREAD

**Issue by macLurker** [NosillaCast/time-adder#7]
If you enter a tab from the last field of any row not the first, a new row gets added. It should only add a row if you tab from the last field of the last row. Tabbing from the last field of the first row does not cause a new row to be added.

Tested on Safari on iPad and MacOS desktop

Sequence to create: reload page (have 2 rows by default). Hit “add another row” button (now have 3 rows). Click on last field of 2nd row. Hit tab. It adds a 4th row.

Second sequence to create: reload page (have 2 rows by default). Click on last field of last (second) row so keyboard focus is there. Hit tab. It adds a 3rd row. All OK so far. Click on last field of second row again so keyboard focus is there. Hit tab again. It adds a 4th row.

**Comment by podfeet** [comment]
Fixed in tag release tabAddRow here:

https://github.com/NosillaCast/time-adder/releases/tag/tabNewRow
